# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.





#this is a dockerfile to create a golden image for JITP with AWS IoT Core
#This is a example file meant only for simulation. Certificate Key should never been tranfered into a container. 


FROM ubuntu
WORKDIR /opt/iotdevice
ADD iotdevice /opt/iotdevice

RUN cd /opt/iotdevice
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install python3 -y
RUN apt install python3-pip -y
RUN apt install wget -y
RUN apt install uuid-runtime -y
RUN pip install -r requirements.txt
RUN wget -O rootcert.pem https://www.amazontrust.com/repository/AmazonRootCA1.pem


RUN apt-get install mosquitto -y
RUN apt-get install mosquitto-clients -y

CMD export DOCKER_ID=$(uuidgen); python3 fleetprovisioning.py --endpoint $ENDPOINT \
    --root-ca rootcert.pem \
    --cert provision-claim.certificate.pem \
    --key provision-claim.private.key \
    --client-id fleet-device \
    --templateName FleetProvisioningTemplate \
    --templateParameters "{\"DeviceName\":\"FPC-device-${DOCKER_ID}\",\"SerialNumber\":\"123456\",\"DeviceLocation\":\"Berlin\"}"; python3 simple_simulator.py

