version: '3'
services:
  cert_signing_service:
    build:
      context: ./cert_signing_service
      dockerfile: Dockerfile.cert_signing_service
    networks:
      - ca_signing_network
    container_name: cert_signing_service

  iot-client:
    build:
      context: ./iot_client
      dockerfile: Dockerfile.iot_client
    environment:
      - IOT_ENDPOINT
    depends_on:
      - cert_signing_service
    networks:
      - ca_signing_network

networks:
  ca_signing_network:
    driver: bridge