
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.



#this is a dockerfile to create a golden image for JITR with AWS IoT Core
#This is a example file meant only for simulation. Certificate Key should never been tranfered into a container. 


FROM ubuntu
WORKDIR /opt/iotdevice
ADD iotdevice /opt/iotdevice

RUN cd /opt/iotdevice
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install python3 -y
RUN apt install openssl
RUN apt install wget -y
RUN apt install uuid-runtime
RUN wget -O AmazonRootCA1.pem https://www.amazontrust.com/repository/AmazonRootCA1.pem


RUN apt-get install mosquitto -y
RUN apt-get install mosquitto-clients -y

CMD export DOCKER_ID=$(uuidgen); 
DEVICE_INFO="/C=US/ST=CO/O=AWS/CN=JITR-device-${DOCKER_ID}"; 
openssl genrsa -out deviceCert.key 2048; openssl req -new -key 
deviceCert.key -out deviceCert.csr -subj $DEVICE_INFO; 
openssl x509 -req -in deviceCert.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out deviceCert.crt -days 365 -sha256; 
cat deviceCert.crt rootCA.pem > deviceCertAndCACert.crt; python3 simple_simulator.py

 